name: Bug report
description: Report a bug.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: bug
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
